### PR TITLE
Update JavaScript references to use the latest `stellar-sdk`

### PR DESCRIPTION
**Pull request by Shaptic**
Reference: https://github.com/stellar/soroban-tools/issues/1048

Pending:
- [x] actually releasing the sdk
- [x] corresponding soroban-tools fixes
- [x] test runs to ensure it all works

### CODE REVIEW

**Comment by sreuland** [comment]
I tried building and running the system-test image but noticed the soroban-rpc build step was failing due to tools Dockerfile needing to be udpated to 1.21 - https://github.com/stellar/soroban-tools/pull/1057/files

**Comment by sreuland** [comment]
@Shaptic , I noticed further issues with latest quickstart image requiring different env variables to be defined during image. build, I've [committed fix here](https://github.com/stellar/system-test/pull/81/commits/c5bf548727742f55edbeb056374eee3b62bbefc1) 

I'm running latest on the PR locally, first build system-test image with what I think is the latest version of core with stable/latest xdr, this is the git ref that was used for `19.14.1-1529.fcbbad4ce.focal` , which mainline soroban-tools uses on rpc integration tests, and this builds rpc and cli with latest from main also:
```
make CORE_GIT_REF=https://github.com/stellar/stellar-core.git#fcbbad4ce7593d5b76c2b4cca883d51b2c702d73 JS_STELLAR_SDK_NPM_VERSION=11.0.0-beta.5 build
```

then I run the tests:
```
docker run --rm -it --name e2e_test stellar/system-test:dev --VerboseOutput true
```

but I'm seeing error in simulate tx web server handler in rpc server:
```
error: transaction simulation failed: host invocation failed
Caused by: HostError: Error(WasmVm, InvalidInput)
```

**Comment by Shaptic** [comment]
@sreuland shoot, okay. I'm not 100% sure about XDR compatibility ([this thread](https://stellarfoundation.slack.com/archives/C030Z9EHVQE/p1697477264919129) has git refs), but the beta.5 is actually for current testnet rather than the current build :confused:

I didn't realize we were updating the system tests to latest xdr also - I was just hoping to migrate them to use the stellar-sdk over soroban-client... In that case I need to push a PR that duplicates https://github.com/stellar/js-soroban-client/pull/167 over to stellar-sdk, but I was hoping not to do that until we actually merged that PR... :disappointed: 

There's two options, I guess:
 - I can kick out a branch on Monday that ports the above PR to the stellar-sdk and use the gitref here or
 - we can _keep_ using soroban-client and try to use the above branch instead to ensure e2e works and THEN port it to stellar-sdk later when that is released

**Comment by sreuland** [comment]
@Shaptic , what's in this pr should still be related to just enabling stellar-sdk usage in system test for any set of soroban platform component versions. Sounds like my attempt to verify these changes which use js-stellar-sdk by building and running system-test with the mainline versions was incorrect state. I let defaults kick in on the build for latest mainline versions of cli/rpc and set core =fcbbad4ce7` and js=11.0.0-beta.5. 

We just need to re-run system-test build from this PR with the correct/matched versions that will work with some version of js-stellar-sdk, should i build using the latest [Preview 11](https://soroban.stellar.org/docs/reference/releases#preview-11-september-11-2023-testnet-and-futurenet-edition) versions for core/rpc/cli and then what version of js-stellar-sdk works with the preview 11? currently js-soroban-client is ref'd for js in preview 11 only.

**Comment by Shaptic** [comment]
> We just need to re-run system-test build from this PR with the correct/matched versions that will work with some version of js-stellar-sdk

@sreuland I think that's right, yeah: [`stellar-sdk`@v11.0.0-beta.5](https://github.com/stellar/js-stellar-sdk/releases/tag/v11.0.0-beta.5) uses XDR that is compatible with the current testnet, so that plus the other versions from the Preview 11 doc _should_ be correct.

**Comment by sreuland** [comment]
I think we'll need https://github.com/stellar/system-test/pull/83 to merge and pull that in here, as tests aren't able to get cli to install a contract due to that rc sdk usage on the soroban-examples.

**Review by sreuland — APPROVED** [review]
solid work!

**Pull request merged**
