### PR TITLE
feat: update to work with new dynamic args

### PR DESCRIPTION
**Pull request by chadoh**
dynamic CLI args under development at https://github.com/stellar/soroban-tools/pull/307

### CODE REVIEW

**Comment by chadoh** [comment]
@sreuland can you review please? (I am not currently allowed to use GitHub's "request review" feature)

**Comment by sreuland** [comment]
@chadoh , would you mind running this version of system test locally against your latest compiled soroban-tools `cli` to confirm tests work as expected? can be done locally in 2 steps(full doc [here](https://github.com/stellar/system-test#run-tests-from-locally-checked-out-repo) for reference):

```
// this runs docker image with soroban services, 
// can run in one terminal, or run as daemonized, 
// it'll print `Tests can now begin` once it's initialized
$ docker run --platform linux/amd64 --rm -it --name e2e_test -p "8000:8000" stellar/system-test:1.0.1 --CoreDebianVersion "19.6.1-1158.c0ad35aa1.focal~soroban" --HorizonDebianVersion "2.22.0~soroban-323" --SorobanRPCDebianVersion 0.4.0-10 --RunTargetStackOnly true

// when the docker prints it's ready for tests, run this from system-test folder in another terminal, 
// will execute the tests using `soroban` cli from your path 
// uses services on 8000 port from docker
system-test$ SorobanExamplesGitHash="main" \
 SorobanExamplesRepoURL="https://github.com/stellar/soroban-examples.git" \
 TargetNetworkPassPhrase="Standalone Network ; February 2017" \
 TargetNetworkSecretKey="SC5O7VZUXDJ6JBDSZ74DSERXL7W3Y5LTOAMRF7RQRL3TAGAPS7LUVG3L" \
 TargetNetworkPublicKey="GBZXN7PIRZGNMHGA7MUUUF4GWPY5AYPV6LY4UV2GL6VJGIQRXFDNMADI" \
 TargetNetworkRPCURL="http://localhost:8000/soroban/rpc" \
 VerboseOutput=true \
 go test -v ./features/dapp_develop/...

```

**Comment by chadoh** [comment]
Thanks for teaching me how to do that, @sreuland! It helped me find a bug, which I've now fixed. My tests pass locally.

**Review by sreuland — APPROVED** [review]
@chadoh , thanks for verifying tests locally, looks good to me! when this merges, then `stellar/system-test:latest` docker tag will be updated, I can also cut a  new release here of `stellar/system-test:1.0.3` that will have this change, which you could set as image reference in e2e.yml of your soroban-tools pr.

**Pull request merged**
